R74mojiData = {
/*"shortcode":["Full Name","closest emoji" or ""] */
  "acne":["Face with Acne",""],
  "adhesive_bandage":["Face with Adhesive Bandage on Forehead",""],
  "angle_frown":["Angle Frown :<",""],
  "angle_smile":["Angle Smile :>",""],
  "angry_cat_emoticon":["Angry Cat Emoticon >:3",""],
  "angry_demon":["Angry Demon",""],
  "angry_imp":["Angry Imp",""],
  "angry_shout":["Angry Shouting",""],
  "angry":["Angry",""],
  "angry2":["Angry with Visible Veins",""],
  "bandana":["Face with Red Bandana",""],
  "bearded":["Bearded Face",""],
  "big_eyes":["Face with Big Eyes",""],
  "big_pupils":["Face with Big Pupils",""],
  "big_smile":["Face with Large Smile",""],
  "bitcoin_eyes":["Face with Bitcoin Eyes",""],
  "biting_lip":["Biting Lip",""],
  "biting_rose":["Face with Rose in Mouth",""],
  "blindfolded":["Blindfolded Face",""],
  "bloodshot_eyes":["Face with Bloodshot Eyes",""],
  "bloodshot_right":["Face with Bloodshot Eyes Looking Right",""],
  "blow_kiss_wink":["Blowing Kiss and Winking",""],
  "blow_kiss":["Blowing Kiss",""],
  "blowing_gum":["Blowing Bubblegum",""],
  "blowing_nose":["Blowing Nose with Tissue",""],
  "blush":["Blushing Smile",""],
  "bracket_frown":["Bracket Frown :[",""],
  "bracket_smile":["Bracket Smile :]",""],
  "break_up":["Face with Broken Hearts",""],
  "broken_heart_eyes":["Face with Broken Heart Eyes",""],
  "broken_heart_face":["Face with Broken Heart",""],
  "bruised_eye":["Face with Bruised Eye",""],
  "brushing_teeth":["Brushing Teeth",""],
  "burp":["Burping Face",""],
  "care":["Hugging Heart",""],
  "cat_emoticon":["Cat Emoticon :3",""],
  "cat":["Cat Face",""],
  "clout_goggles":["Face with Clout Goggles",""],
  "clown":["Clown",""],
  "cold_face":["Frozen Face",""],
  "cold_face2":["Cold Face",""],
  "cold_sweat":["Cold Sweat",""],
  "cold_sweat2":["Cold Sweat (Yellow Face)",""],
  "covering_ears":["Face with Hands over Ears",""],
  "covering_eye":["Face with Hands over Right Eye",""],
  "covering_eyes":["Face with Hands over Eyes",""],
  "cowboy":["Face with Cowboy Hat",""],
  "cracked_head":["Cracked Head",""],
  "crazy_eyes":["Face with Crazy Eyes",""],
  "creepy_smile":["Creepy Smile",""],
  "cross_eyed":["Cross-Eyed Face",""],
  "cry":["Face with Tear",""],
  "cussing":["Face with Symbols over Mouth",""],
  "cussing2":["Face with Symbols over Mouth (Yellow)",""],
  "dead_face_mask":["Dead Face with Face Mask",""],
  "dead_ghost":["Dead Face with Ghost in Mouth",""],
  "dead_head_bandage":["Dead Face with Head Bandages",""],
  "dead_nosebleed":["Dead Face with Nosebleed",""],
  "dead":["Dead Face",""],
  "desolate":["Desolate Face",""],
  "despair":["Face of Despair",""],
  "despair2":["Face of Slight Despair",""],
  "different_eyes":["Face with Different-Sized Eyes",""],
  "disappointed":["Disappointed Face",""],
  "disguised":["Face with Disguised",""],
  "disgusted_tongue":["Disgusted Face with Tongue Out",""],
  "disgusted":["Disgusted Face",""],
  "dizzy_star":["Face with Revolving Star",""],
  "dizzy":["Dizzy Face",""],
  "drool":["Drooling Face",""],
  "dunce":["Face with Dunce Cap",""],
  "eating_pizza":["Face Eating Pizza",""],
  "embarassed":["Embarassed Face",""],
  "emo":["Face with Emo Hair",""],
  "envy":["Angry Envious Face",""],
  "epic":["Epic Face",""],
  "epic2":["Epic Face with Closed Mouth",""],
  "euro_tongue":["Face with Euro Eyes and Tongue",""],
  "evil_demon":["Evil Demon",""],
  "evil_imp":["Evil Imp",""],
  "evil":["Evil Face",""],
  "exhale":["Face Exhaling",""],
  "exploding_head":["Face with Exploding Head",""],
  "eyebrow_raised":["Face with Eyebrow Raised",""],
  "eyepatch":["Face with Eyepatch",""],
  "face_mask_white":["Face with White Face Mask",""],
  "face_mask":["Face with Face Mask",""],
  "face_shield":["Face with Face Shield",""],
  "faceless":["Faceless Head",""],
  "fart":["Farting Face",""],
  "fearful":["Fearful Face",""],
  "fearful2":["Fearful Face (Yellow)",""],
  "fever":["Sweating Face with Thermometer",""],
  "fire_eyes":["Face with Flaming Eyes",""],
  "flaming_face":["Dead Face on Fire",""],
  "flat_eyes_mouthless":["Face with Flat Eyes and No Mouth",""],
  "flat_eyes":["Face with Flat Eyes",""],
  "floating_question_marks":["Face with Floating Question Marks",""],
  "floating_star":["Face with Floating Star",""],
  "flushed_inflated":["Inflated Flushed Face",""],
  "flushed_nosebleed":["Flushed Face with Nosebleed",""],
  "flushed_sweating":["Sweating Flushed Face",""],
  "flushed":["Flushed Face",""],
  "frown_left":["Frown Pointing Left",""],
  "frown_right":["Frown Pointing Right",""],
  "frown":["Frowning Face",""],
  "frown2":["Slightly Frowning Face",""],
  "gas_mask":["Face with Gas Mask",""],
  "gasp":["Gasping Face",""],
  "giggle":["Giggling Face with Hand over Mouth",""],
  "glass_head":["Face with Glass Head",""],
  "glasses_push":["Face Pushing Glasses",""],
  "glasses":["Face with Glasses",""],
  "grimace":["Grimacing Face",""],
  "grin":["Happy Grin Face",""],
  "grinning":["Grinning Face",""],
  "grinning2":["Happy Grinning Face",""],
  "halo":["Face with Halo",""],
  "happy_cussing":["Face Cussing Happily",""],
  "happy_grimace":["Happy Grimacing Face",""],
  "happy_surprised":["Happy Surprised Face",""],
  "happy_tear":["Happy Face with Tear",""],
  "happy":["Very Happy Face",""],
  "happy2":["Happy Face",""],
  "happy3":["Slightly Happy Face",""],
  "head_bandage":["Face with Head Bandages",""],
  "head_in_clouds":["Face in Clouds",""],
  "headphones":["Face with Headphones",""],
  "heart_eyes_smile":["Smiling Face with Heart Eyes",""],
  "heart_eyes":["Face with Heart Eyes",""],
  "heart_eyes2":["Face with Vertical Heart Eyes",""],
  "hehe":["Giggling Looking Top-Right",""],
  "hot_face":["Hot Face",""],
  "hug":["Hugging Face",""],
  "hush":["Shushing Face",""],
  "idea":["Face with Idea Lightbulb",""],
  "in_love":["Face with Floating Hearts",""],
  "inhale":["Face Inhaling Happily",""],
  "jealous":["Frown of Jealous",""],
  "joy":["Laughing with Tears of Joy",""],
  "kappa":["Kappa",""],
  "kiss_left":["Kissing to Left",""],
  "kiss_right":["Kissing to Right",""],
  "kiss_smile":["Kissing Smile Face",""],
  "kiss_wink":["Kissing Winking Face",""],
  "kiss":["Kissing Face",""],
  "kiss2":["Calm Kissing Face",""],
  "laughing":["Laughing Face",""],
  "lenny":["Lenny Face",""],
  "love_face":["Face with Floating Heart",""],
  "lul":["Laughing with Finger on Chin",""],
  "lying":["Face with Long Nose",""],
  "meh":["Meh Face",""],
  "melting_face":["Melting Face",""],
  "money_eyes":["Face with Dollar Eyes",""],
  "money_tongue":["Face with Dollar Eyes and Tongue",""],
  "monocle":["Face with Monocle",""],
  "moon_face":["Moon Face",""],
  "mouthless":["Mouthless Face",""],
  "mustache":["Face with Mustache",""],
  "nausea":["Nauseated Face",""],
  "nausea2":["Nauseated Face (Yellow)",""],
  "nerd":["Nerd Face",""],
  "neutral":["Neutral Face",""],
  "new_year_glasses":["Face with 2020 New Year Glasses",""],
  "ninja":["Ninja",""],
  "nodding_yes":["Face Nodding Yes",""],
  "nose_face":["Face with Visible Nose",""],
  "nosebleed":["Face with Nosebleed",""],
  "ok_face":["Face with OK Eyes",""],
  "oops":["Surprised Face with Hand over Mouth",""],
  "oops2":["Slightly Surprised Face with Hand over Mouth",""],
  "pacifier":["Face with Baby Pacifier",""],
  "pacman":["PAC-MAN",""],
  "party_hat_face":["Face with Party Hat",""],
  "party_horn_face":["Face blowing Party Horn",""],
  "party":["Partying Face",""],
  "peeking":["Face Peeking Through Hands",""],
  "pensive_cowboy":["Sad Cowboy",""],
  "pensive_flushed":["Pensive Flushed Face",""],
  "pensive_headphones":["Pensive Face with Headphones",""],
  "pensive":["Pensive",""],
  "pirate_hat":["Face with Pirate Hat",""],
  "pirate":["Pirate",""],
  "pirate2":["Pirate with Bandana",""],
  "pleading":["Pleading Face",""],
  "pogchamp":["Surprised Face to Right",""],
  "poggers":["Surprised Face to Left",""],
  "pound_tongue":["Face with Pound Eyes and Tongue",""],
  "powercry":["Powercry Face",""],
  "question_mark_eyes":["Face with Question Mark Eyes",""],
  "question_mark_face":["Face with Floating Question Mark",""],
  "rage_steaming":["Angry Face Steaming",""],
  "rage":["Raging Face",""],
  "rainbow_sunglasses":["Face with Rainbow Sunglasses",""],
  "really":["Disappointed in You face",""],
  "relaxed":["Relaxed Face",""],
  "relieved":["Relieved Face",""],
  "rofl":["Rolling on the Floor Laughing",""],
  "rolling_eyes_smile":["Rolling Eyes and Smiling",""],
  "rolling_eyes_up":["Face with Eyes Looking Up",""],
  "rolling_eyes":["Face Rolling Eyes",""],
  "running_nose":["Face with Running Nose",""],
  "sad_covering_ears":["Sad Face with Hands over Ears",""],
  "sad_face_mask":["Sad Face with Face Mask",""],
  "sad_hug":["Sad Hugging Face",""],
  "sad_rage":["Half Sad Half Angry Face",""],
  "sad_relieved":["Sad but Relieved Face",""],
  "sad_relieved2":["Sad but Relieved Face (Blue)",""],
  "sad_sweat":["Sad Face with Cold Sweat",""],
  "sad":["Sad Face",""],
  "santa_hat":["Face with Santa Hat",""],
  "santa_party":["Face with Santa Hat Partying",""],
  "santa":["Santa Claus",""],
  "scream":["Screaming Face",""],
  "serious_sunglasses":["Serious Face with Sunglasses",""],
  "shaking_no":["Face Shaking Head No",""],
  "shamrock_eyes":["Face with Shamrock Eyes",""],
  "shocked":["Shocked Face with Eyebrows Raised",""],
  "shocked2":["Shocked Face",""],
  "sick":["Face with Thermometer",""],
  "silly":["Winking Face with Tongue Out",""],
  "ski_mask":["Face with Ski Mask",""],
  "slash_mouth":["Slash Mouth Emoticon :/",""],
  "sleep_deprived":["Sleep Deprived",""],
  "sleeping_ghost":["Sleeping Face with Ghost",""],
  "sleeping":["Sleeping Face",""],
  "sleepy_eyes":["Face with Sleepy Eyes",""],
  "sleepy":["Sleepy Face",""],
  "slight_meh":["Slight Meh Face",""],
  "slight_whistle":["Face Whistling Slightly",""],
  "small_pupils":["Face with Small Pupils",""],
  "smile_down":["Face Smiling Down",""],
  "smile_left":["Face Smiling to Left",""],
  "smile_right":["Face Smiling to Right",""],
  "smile_up":["Face Smiling Up",""],
  "smile":["Smiling Face",""],
  "smiley":["Smiling Face with Mouth Open",""],
  "smirk":["Smirking Face",""],
  "smoking_cigar":["Face Smoking Cigar",""],
  "smoking_pipe":["Face Smoking Pipe",""],
  "smoking":["Face Smoking Cigarette",""],
  "smug":["Smug Face",""],
  "snowman":["Snowman Face",""],
  "sob_clown":["Sobbing Clown",""],
  "sob_despair":["Sobbing Face of Despair",""],
  "sob_party":["Sobbing Partying Face",""],
  "sob_sunglasses":["Sobbing Face with Sunglasses",""],
  "sob":["Sobbing Face",""],
  "sob2":["Sobbing Face with Shiny Eyes",""],
  "squint_frown":["Squinting Frowning Face",""],
  "squint_grimace":["Squinting Grimacing Face",""],
  "squint_kiss":["Squinting Kissing Face",""],
  "squint_open_mouth":["Squinting Face with Mouth Open",""],
  "squint_smile":["Squinting Smiling Face",""],
  "squint_tongue":["Squinting Face with Tongue Out",""],
  "squint":["Squinting Face in Disgust",""],
  "star_eyes":["Starstruck Face",""],
  "stubble":["Face with Stubble Beard",""],
  "sunglasses":["Face with Sunglasses",""],
  "surprised":["Surprised Face",""],
  "suspicious":["Suspicious Face to Right",""],
  "suspicious2":["Suspicious Face to Left",""],
  "sweat_smile":["Smile Face with Sweat Drop",""],
  "sweating":["Sweating Face",""],
  "talking":["Talking Face with Speech Balloon",""],
  "tangled_lights":["Face Tangled in Holiday Lights",""],
  "tears_of_joy":["Face Holding Back Tears of Joy",""],
  "tears_of_joy2":["Grinning Face Holding Back Tears of Joy",""],
  "terrified":["Terrified Face",""],
  "thinking":["Thinking Face",""],
  "thonk":["Thonk Face",""],
  "tiny_neutral":["Tiny Neutral Face",""],
  "tiny_smile_blush":["Blushing Face with Tiny Smile",""],
  "tired":["Tired Face",""],
  "tongue_out":["Face with Tongue Out",""],
  "triumph":["Face of Triumph",""],
  "unamused":["Unamused Face",""],
  "underwater_head":["Squinting Face Underwater",""],
  "upside_down_frown":["Upside-Down Frowning Face",""],
  "upside_down_neutral":["Upside-Down Neutral Face",""],
  "upside_down":["Upside-Down Smiling Face",""],
  "uwu":["UwU Emoticon",""],
  "vomiting":["Vomiting Face",""],
  "vomiting2":["Vomiting Face (Yellow)",""],
  "wall_eyed":["Walleyed Face",""],
  "weary":["Weary Face",""],
  "whistling":["Face Whistling",""],
  "white_eyes":["Face with No Pupils",""],
  "wide":["Wide Smiling Face",""],
  "wink_cry":["Crying Face Winking",""],
  "wink_frown":["Frowning Face Winking",""],
  "wink":["Winking Face",""],
  "woozy":["Woozy Face",""],
  "worried":["Worried Face",""],
  "worried2":["Worried Face (Blue)",""],
  "wrapped":["Gift-Wrapped Face",""],
  "xd":["xD Emoticon",""],
  "xok":["Xok Face",""],
  "yawn":["Yawning Face",""],
  "yen_tongue":["Face with Yen Eyes and Tongue",""],
  "yum":["Smiling Face with Tongue Out",""],
  "zany":["Zany Face",""],
  "zipper_mouth":["Face with Mouth Zippered Shut",""],
  //"":["",""]
}
/*
a = "";
for (var i in l) {
  a += '  "'+l[i]+'":["'+l[i]+'",""],\n'
}
*/
ValidR74mojiAttributes = ["type"]

function createPlaceholder() {/*https://stackoverflow.com/a/7004837/8234438*/
  var img = document.createElement('img');
  img.setAttribute('style', 'width:100%;height:100%;border:none;display:block');
  img.src = 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
  return img;
}

window.addEventListener("load",function(){
  var EmojiTagList = document.getElementsByTagName("emoji");
  for (i = 0; i < EmojiTagList.length; ++i) {
    var OriginalEmojiTag = EmojiTagList[i];
    var EmojiTag = document.createElement("img");

    for(var n in OriginalEmojiTag.attributes){/*transfer relevant attributes*/
      var k = OriginalEmojiTag.attributes[n];
      if (ValidR74mojiAttributes.includes(k.name)){
        EmojiTag.setAttribute(k.name,OriginalEmojiTag.getAttribute(k.name));
        OriginalEmojiTag.removeAttribute("type");
      }
    }

    OriginalEmojiTag.appendChild(EmojiTag);
    OriginalEmojiTag.setAttribute("loaded","true");


    var EmojiType = EmojiTag.getAttribute("type");

    if (!(R74mojiData[EmojiType]==undefined)) {
      var ImageURL = "https://r74n.com/moji/png/"+EmojiType+".png"
    }
    else {var ImageURL = "https://r74n.com/moji/png/faceless.png"}
    EmojiTag.setAttribute("src",ImageURL);
    EmojiTag.style.width = "1.75em";
    EmojiTag.style.height = "1.75em";
    EmojiTag.style.minWidth = "1em";
    EmojiTag.style.minHeight = "1em";
    EmojiTag.style.display = "inline-block";
    EmojiTag.style.verticalAlign = "middle";
    EmojiTag.style.marginBottom = "0.3em";
    EmojiTag.style.cursor = "text";
    EmojiTag.setAttribute("title",R74mojiData[EmojiType][0]);
    if (R74mojiData[EmojiType][1]=="") {
      EmojiTag.setAttribute("alt","[?]");
    }
    else {
      EmojiTag.setAttribute("alt",R74mojiData[EmojiType][1]);
    }
    EmojiTag.style.webkitUserDrag = "none";
    EmojiTag.style.userDrag = "none";

  }



})