heads = {
'chocodogmask.png': 'Dog with Chocolate (Lanc3y and Rookrar2k19)',
'lanceypog.png': 'Lanc3y Pog (Lanc3y and Rookrar2k19)',
'meesixlogo.png': 'Mee6 Logo (Lanc3y and Rookrar2k19)',
'okayeggsreq.png': 'okayeggsreq (Lanc3y and Rookrar2k19)',
'minireactorcore.png': 'Nether Reactor Core (Lanc3y and Rookrar2k19)',
'weirdfacelol.png': '??? (Lanc3y and Rookrar2k19)',
'whatisthisgaming.png': '??? (Lanc3y and Rookrar2k19)',
'shulkerthing.png': 'Shulker (Lanc3y and Rookrar2k19)',
'akari.png': 'Akari Akaza (Lanc3y and Rookrar2k19)',
'dogsmilinglol.png': 'Smiling Dog (Lanc3y and Rookrar2k19)',
'realisitcsteve.png': 'Realistic Steve (Lanc3y and Rookrar2k19)',
'whatisthisposedtobe.png': 'Pikachu (Lanc3y and Rookrar2k19)',
'oldjoke.png': 'oldjoke (Lanc3y and Rookrar2k19)',
'eyeballtexturev2.png': 'Eyeball (Lanc3y and Rookrar2k19)',
'squarehead.png': 'Square Grid Head (Lanc3y and Rookrar2k19)',
'kittycatty.png': 'Cat (Lanc3y and Rookrar2k19)',
'nerdmc.png': 'Steve with Glasses (Lanc3y and Rookrar2k19)',
'badbadbadbadbad.png': 'Grantare Productions (Lanc3y and Rookrar2k19)',
'lanceyyy.png': 'Lanc3y (Lanc3y and Rookrar2k19)',
'willywalter.png': 'WillyWalter (Lanc3y and Rookrar2k19)',
'spongebobmeboy.png': 'Sponge (Lanc3y and Rookrar2k19)',
'spiritgame.png': 'Spirit Game (Lanc3y and Rookrar2k19)',
'weirdegg.png': 'Bedrock NPC Spawn Egg (Lanc3y and Rookrar2k19)',
'undoguy.png': 'undoguy (Lanc3y and Rookrar2k19)',
'greenappl.png': 'Green Apple (Lanc3y and Rookrar2k19)',
'alienwood.png': 'Green Wooden Planks (Lanc3y and Rookrar2k19)',
'blockofcat.png': 'Block of Cat (Lanc3y and Rookrar2k19)',
'RyanUwUTrans.png': 'Transgender Flag (RyanUwU)',
'RyanUwURainbow.png': 'Rainbow (RyanUwU)',
'vendetta.png': 'Anonymous Hacker Mask',
'MinerHat1_LeoTheRavioli.png': 'Miner Hat (LeoTheRavioli)',
'PirateHat2_LeoTheRavioli.png': 'Pirate Hat (LeoTheRavioli)',
'Mask1_LeoTheRavioli.png': 'Mask 1 (LeoTheRavioli)',
'instinctuallinus.png': 'LinusTechTips (instinct)',
'3DGLASSES.png': '3D Glasses (Runaiic)',
'ShephardHat_LeoTheRavioli.png': 'Shepherd Hat (LeoTheRavioli)',
'SantaHat1_LeoTheRavioli.png': 'Santa Hat (LeoTheRavioli)',
'Sunglasses1_LeoTheRavioli.png': 'Sunglasses 1 (LeoTheRavioli)',
'Sunglasses2_LeoTheRavioli.png': 'Sunglasses 2 (LeoTheRavioli)',
'Samurai_v2_LeoTheRavioli.png': 'Samurai Hat (LeoTheRavioli)',
'RussianHat_LeoTheRavioli.png': 'Russian Hat (LeoTheRavioli)',
'WarriorHat1_LeoTheRavioli.png': 'Warrior Hat (LeoTheRavioli)',
'TaigaHat_LeoTheRavioli.png': 'Taiga Hat (LeoTheRavioli)',
'sunglasses2.png': 'Pixel Sunglasses (Higher) (Lisa1051)',
'emerald-armor-try-2.png': 'Emerald Helmet',
'Tech3_LeoTheRavioli.png': 'Tech 3 (LeoTheRavioli)',
'NurseHat_LeoTheRavioli.png': 'Nurse Hat (LeoTheRavioli)',
'Piratehat1_LeoTheRavioli.png': 'Pirate Hat (LeoTheRavioli)',
'LibrarianHat_LeoTheRavioli.png': 'Librarian Hat (LeoTheRavioli)',
'MajorasMask_LeoTheRavioli.png': "Majora's Mask (LeoTheRavioli)",
'Tech2_LeoTheRavioli.png': 'Tech 2 (LeoTheRavioli)',
'WitchHat_LeoTheRavioli.png': 'Witch Hat (LeoTheRavioli)',
'MilitaryHat_LeoTheRavioli.png': 'Military Hat (LeoTheRavioli)',
'MilkmanHat_LeoTheRavioli.png': 'Milkman Hat (LeoTheRavioli)',
'MinerHat2_LeoTheRavioli.png': 'Miner Hat (LeoTheRavioli)',
'Tech1_LeoTheRavioli.png': 'Tech 1 (LeoTheRavioli)',
'uwu.png': 'UwU Blush',
'owo1.png': 'owo',
'cutecat.png': 'Cat Filter',
'smile7_LeoTheRavioli.png': 'Blushing with Lips (LeoTheRavioli)',
'smile4_LeoTheRavioli.png': 'Lips (LeoTheRavioli)',
'smile3_LeoTheRavioli.png': 'Lips 2 (LeoTheRavioli)',
'smile1_LeoTheRavioli.png': 'Scary Stare (LeoTheRavioli)',
'smile8_LeoTheRavioli.png': 'Emoji Lips 👁👄👁 (LeoTheRavioli)',
'smile6_LeoTheRavioli.png': 'Blushing with Lips 2 (LeoTheRavioli)',
'smile5_LeoTheRavioli.png': 'Blushing Smile (LeoTheRavioli)',
'RyanUwUHotdogK.png': 'Hotdog with Ketchup (RyanUwU)',
'RyanUwUBeacon.png': 'Beacon (RyanUwU)',
'RyanUwUJahseh2.png': 'xxxTentacion Jahseh Onfroy (RyanUwU)',
'RyanUwUYun.png': 'Yun Iijima New Game (RyanUwU)',
'RyanUwUBean2.png': 'Astolfo Bean (RyanUwU)',
'RyanUwUHotdog.png': 'Hotdog (RyanUwU)',
'RyanUwUNene.png': 'Nene Sakura New Game (RyanUwU)',
'RyanUwUHamburger.png': '4K Hamburger (RyanUwU)',
'RyanUwUTohru.png': 'Tohru Kobayashi Dragon Maid (RyanUwU)',
'RyanUwUKiss2.png': 'Kiss Your Homies Goodnight 1 (RyanUwU)',
'RyanUwUKiss1.png': 'Kiss Your Homies Goodnight 2 (RyanUwU)',
'RyanUwUDoge.png': 'Sad Doge (RyanUwU)',
'RyanUwUPogU.png': 'PogU (RyanUwU)',
'RyanUwUEmoji.png': 'Staring Left Emoji (RyanUwU)',
'RyanUwUCry.png': 'Crying Emoji (RyanUwU)',
'RyanUwULink.png': 'Link (RyanUwU)',
'RyanUwUBeg.png': 'Begging Emoji (RyanUwU)',
'RyanUwUFlushed.png': 'Flushed Emoji (RyanUwU)',
'RyanUwUFlushed2.png': 'Omega Flushed Emoji (RyanUwU)',
'pewdiepie.png': 'PewDiePie',
'reedot.png': 'Reddit Logo',
'RyanUwUBean.png': 'Astolfo Bean Flat (RyanUwU)',
'airpodss-1.png': 'AirPods',
'RyanUwUPus.png': 'Platypus (RyanUwU)',
'839957-MBP.png': 'MacBook Pro (courteously)',
'prototech-player-head.png': 'ProtoTech (nsap)',
'Head-BD-Dva.png': 'NSFW Belle Delphine Ahegao',
'nok.png': 'nok',
'KITTY-1.png': 'White Cat (Runaiic)',
'RyanUwUOwO.png': 'NSFW Hentai (RyanUwU)',
'Skull.png': 'Creepy Skull',
'TestTest.png': 'Pepe Crying with Gun',
'shutupTRAMP.png': 'Shut Up N-Word Penguin',
'pepele.png': 'NSFW Anime Girl Ass',
'pinkdude.png': 'Pink Guy',
'pepeomg.png': 'Buff Pepe Feels Good',
'blackdudehead.png': '??? Man',
'nogo.png': 'NSFW/L Hentai Tuba Shoved Up...',
'deezcord.png': 'Discord Logo',
'privacyinvader.png': 'Facebook Logo',
'instakilogram.png': 'Instagram Logo',
'snapchat.png': 'Snapchat',
'twitsh.png': 'Twitch Logo',
'twatter.png': 'Twitter Logo',
'wuddap-1.png': 'WhatsApp Logo',
'nixietube.png': 'YouTube Logo',
'Head-PDP-Sub.png': 'Subscribe to PewDiePie',
'gggggggggggg-528x450.png': 'MrBeast',
'sethshead1.png': 'Seth',
'user-avatars/smith-anderson/guy_1.png': 'Buff Man',
'HDFatGuyHead.png': 'Mark Hungry',
'biblerulehasaheadnow.png': 'BibleRule',
'trent.png': '??? Man',
'defaultdance.png': 'Default Dance',
'morgz.png': 'Morgz Mom',
'dad3.png': 'Naruto',
'RAMSAY-HEAD-MASK.png': 'Gordon Ramsay Mask',
'clintonmstr.png': 'Bill Clinton',
'Marziepie.png': 'PewDiePie and Marzia',
'sexymotomoto.png': 'Fat Breaking Bad',
'babysuccess.png': 'Success Baby Meme',
'shrekwork.png': 'Shrek',
'slendytubbies_3_texture_pack-512x450.png': 'Slendytubbies',
'majorasmask_800x450_final.png': "Majora's Mask (Bad)",
'galaxy.png': 'Galaxy AirPods',
'Crown-2.png': 'Pixel Crown',
'Edith-6.png': 'Glasses',
'rainbow_800x450_final.png': 'Rainbow (M-Seven)',
'sadcat.png': 'Sad Cats',
'Head-PDP-Pattern-1.png': 'PewDiePie Pattern',
'lulgod-800x450.png': 'Moana Maui Goomba',
'basse1337.png': 'Penguin You Have Just Summoned God',
'testairgg.png': 'AirPods',
'kasteel_800x450_final.png': 'Kasteel',
'redstone-armor-try-2.png': 'Redstone Helmet',
'spukresized.png': 'Pumpkin Helmet',
'alextheoof.png': 'Emerald Helmet',
'greenhelmet.png': 'Green Helmet',
'darkdd.png': 'Blue Helmet',
'darkhelmet.png': 'Blue Helmet',
'prismarineHelmet-resized.png': 'Prismarine Helmet',
'purhelmet.png': 'Purple Helmet',
'pinkhelmet.png': 'Pink Helmet',
'COW_MOO_MOO_MOO.png': 'Cow 3D Model',
'kitty3.png': 'Cat Filter',
'deer.png': 'Deer Filter',
'bow-1.png': 'Pink Bowtie',
'animeeyes.png': 'Anime Eyes',
'ake_head.png': '??? Man',
'TFHead.png': 'TotalFreedom',
'unicorn.png': 'Unicorn Filter',
'bunnyhead.png': 'Bunny Filter',
'greenornament.png': 'Green Ornament',
'tiara.png': 'Tiara',
'pinkrazerblade.png': 'Pink Laptop (Panther)',
'snowflake.png': 'White Fox Filter',
'blushykitty.png': 'Cat Blushing Filter (Panther)',
'glock17.png': 'Gun (Runaiic)',
'MiniLeaves.png': 'Oak Leaves',
'corrupt.png': 'Corrupt (DogeisCut)',
'tryx38aio9-NEO.png': 'Neo (courteously)',
'orangehelmet.png': 'Orange Helmet',
'invis.png': 'Invisible (Runaiic)',
'roc.png': 'Taiwan Flag',
'holohead_pumpkin.png': 'Holographic Pumpkin (HoloHeads)',
'shrek-2.png': 'Shreak Face',
'896433-tf_bad.png': 'TotalFreedom Sucks (courteously)',
'3922110-animeyes.png': 'Anime Eyes (courteously)',
'392409290-e_meme.png': 'Letter E (courteously)',
'Horror-witch.png': 'Scary Witch',
'thebest-2-1.png': 'Eyeball',
'trollingman124.png': 'Troll Face (TB40)',
'funkydawg.png': 'Happy Dog (instinct)',
'iamlooking.png': 'I Am Looking Emoji (instinct)',
'spinningcatcube.png': 'Spinning Cat (instinct)',
'funnygangstermoment.png': 'YandereDev (instinct)',
'ploggchamp.png': 'PogChamp (instinct)',
'0.png': 'Number 0 (Zero)',
'1-22.png': 'Number 1 (One)',
'2-12.png': 'Number 2 (Two)',
'3-16.png': 'Number 3 (Three)',
'4-15.png': 'Number 4 (Four)',
'5-15.png': 'Number 5 (Five)',
'6-14.png': 'Number 6 (Six)',
'7-3.png': 'Number 7 (Seven)',
'8.png': 'Number 8 (Eight)',
'9-2.png': 'Number 9 (Nine)',
'1-18.png': 'ZZZ Warning Sign',
'1-20.png': 'Anime Skirt',
'1-23.png': 'XYŃ',
'1-24.png': 'Anime :< Face',
'1-25.png': 'Sad Cat',
'1-27.png': 'Shrek Smiling',
'1-28.png': 'Pixel Glasses',
'2-14.png': 'Pixel Glasses (Duplicate)',
'3-17.png': 'Pixel Glasses (Duplicate)',
'1-29.png': 'Purple Rewind Time Symbol',
'1-30.png': 'Forever Alone',
'001.png': 'Ricardo',
'2-9.png': 'Globe Warning Sign',
'2-10.png': 'Anime Sky',
'3-14.png': 'Anime Sky 2',
'4-11.png': 'Anime Sky 3',
'5-14.png': 'Anime Sky 4',
'6-11.png': 'Anime Sky 5',
'6-12.png': 'Anime Sky 6',
'6-13.png': 'Anime Sky 7',
'12-2.png': 'Anime Sky with Bird',
'2-13.png': 'Scary Yelling Face',
'01.png': '???',
'02-1.png': '??? (Duplicate)',
'03.png': '??? (Duplicate)',
'04.png': '??? (Duplicate)',
'05.png': '??? (Duplicate)',
'06.png': '??? (Duplicate)',
'07.png': '???',
'08.png': '???',
'09.png': '???',
'10-2.png': '???',
'11-3.png': '???',
'12-3.png': '???',
'3-15.png': 'Backpack Warning Sign',
'4-10.png': 'Skull Warning Sign',
'5-13.png': 'Parachute Warning Sign',
'5-16.png': 'Parachute Warning Sign (Duplicate)',
'5-17.png': 'Parachute Warning Sign (Duplicate)',
'9-3.png': 'Clock',
'11-4.png': '??? Boy',
'25-1.png': '??? Boy',
'aaa.png': '??? Boy',
'a-2.png': '??? Boy Yelling',
'12-4.png': 'Anti-Russia Flag',
'13-3.png': '???',
'14-1.png': '???',
'15-2.png': '???',
'16.png': '???',
'17.png': '???',
'18.png': '???',
'19.png': '???',
'20.png': '???',
'21-1.png': '???',
'22-1.png': '???',
'23-1.png': '???',
'24-1.png': '???',
'25.png': '???',
'26-2.png': '???',
'50.png': 'JoJo Text',
'111-1.png': 'Square Corners',
'111-2.png': 'Iron Furnace',
'111-3.png': 'Iron Furnace (Duplicate)',
'111-4.png': 'Iron Furnace (Duplicate)',
'111.png': 'Unknown Anime Man',
'444.png': 'Putin',
'a-1.png': 'CallMeCarson Mask (Duplicate)',
'a.png': 'CallMeCarson Mask',
'aaaa.png': 'NSFW Porn FirstAnal (Duplicate)',
'abc-1.png': 'Tiny Mask',
'abc.png': 'Tiny Mask (Not Transparent)',
'ah.png': 'Gordon Ramsay',
'amazing.png': 'Discord Message',
'bitch.png': 'Discord Message in Minecraft',
'america.png': 'Iron-Man',
'angry.png': 'Angry Face (Runaiic)',
'attention.png': "Attention! You're Gay",
'b.png': '??? Cat',
'batman-1.png': 'Batman Mask (Drawn)',
'batman.png': 'Batman Mask',
'batman-2.png': 'Batman Mask (Duplicate)',
'bb.png': 'Red Bull Can',
'bean.png': 'Cursed Beans',
'bedrock-1.png': 'Bedrock',
'bee.png': 'Bee',
'big.png': 'Blue Roblox Head',
'billy.png': 'Billy Herrington',
'billy-1.png': 'Billy Herrington (Duplicate)',
'billy-2.png': 'Billy Herrington (Duplicate)',
'billy-3.png': 'Billy Herrington (Duplicate)',
'billy-4.png': 'Billy Herrington (Duplicate)',
'bow.png': 'Red Bowtie',
'box-1.png': 'Skull Box',
'box.png': 'White Box Black Outline',
'bread.png': 'Bread',
'bunny.png': 'Communist Bugs Bunny',
'carl.png': 'Carl Wheezer Heading Out',
'cats.png': 'Cat AirPods',
'char-1.png': 'Anime Girl',
'char-2.png': '???',
'char-3.png': '???',
'char-4.png': '??? Boy Vaping',
'char-6.png': 'Boy Vaping (Duplicate)',
'char-7.png': 'Boy Vaping (Duplicate)',
'char-8.png': 'Boy Vaping (Duplicate)',
'char-9.png': 'Boy Vaping (Duplicate)',
'char-5.png': 'Sans with Gun',
'char.png': '??? Boy',
'chess.png': 'Chess Board',
'cj.png': 'GTA CJ',
'clear.png': 'Invisible',
'colors.png': 'Side Colors (Runaiic)',
'convict.png': 'Prisoner Hat (Black and White Stripes)',
'cookie.png': 'Cookie',
'copper_ore.png': 'Copper Ore',
'cow-4.png': 'Cow Sphere Head',
'cow-5.png': 'Cow Sphere Head',
'cow-6.png': 'Cow Sphere Head',
'cow-7.png': 'Cow Sphere Head',
'cow-9.png': 'Cow Sphere Head',
'cow-10.png': 'Cow Sphere Head',
'cow-11.png': 'Cow Sphere Head',
'cow-12.png': 'Cow Sphere Head',
'cow-13.png': 'Cow Sphere Head',
'cow.png': 'Cow Sphere Head',
'creeper-1.png': 'Creeper Head',
'creeper.png': 'Cute Creeper Head',
'crown.png': 'Flower Crown',
'cum.png': 'Cum',
'dad.png': 'Fox',
'daddy-1.png': 'Daddy Thistle Sign',
'daddy.png': 'iPhone with Minecraft',
'dan.png': '??? Boy',
'dddd.png': '??? Meme',
'dead.png': "I'm Dead Inside",
'def.png': 'Putin and Obama',
'den-1.png': '??? Boy (Duplicate)',
'den.png': '??? Boy',
'denied.png': 'Fox Filter',
'devil.png': 'Devil',
'diana-1.png': '??? Girl',
'diana.png': 'Pixel Princess',
'dirt.png': 'Dirt Block',
'dodge.png': 'Doge',
'download-9.png': '??? Sonic',
'drive.png': 'C Drive',
'earth.png': 'Minecraft Earth Exclusive Skin',
'egg.png': 'You Just Got Egged',
'emeraldhelmet.png': 'HD Emerald Helmet',
'empty-1.png': 'White (Duplicate)',
'empty-2.png': 'White (Duplicate)',
'empty.png': 'White',
'epic-1.png': 'Minecraft Discord (Duplicate)',
'epic-2.png': 'Minecraft Discord (Duplicate)',
'epic.png': 'Minecraft Discord',
'face.png': 'Knight Face',
'face-1.png': 'Knight Face (Duplicate)',
'fairy.png': '??? Fairy',
'ffff.png': 'Industrial Machine',
'ffff-1.png': 'Industrial Machine (Duplicate)',
'final.png': '??? Man',
'first.png': 'NSFW Anime Boob Covered (Paralusion)',
'flex.png': 'Pp',
'flowers.png': 'Flower Crown with Glasses',
'forward-1.png': '??? Minecraft Character (Duplicate)',
'forward.png': '??? Minecraft Character',
'four.png': 'Chinese Four',
'fruit.png': 'Fruits',
'fruit-1.png': 'Fruits (Duplicate)',
'gay-1.png': '??? Boy',
'gay.png': 'Weird Shrek Face',
'glass.png': 'Glass Block',
'globe.png': 'Globe with Color Sides',
'redornament.png': 'Red Ornament',
'blueornament.png': 'Blue Ornament',
'yellowornament.png': 'Yellow Ornament',
'penguinhat.png': 'Penguin Hat',
'chickenhat.png': 'Chicken Hat',
'melonhat.png': 'Melon Hat',
'gold-1.png': 'Gold AirPods (Duplicate)',
'gold.png': 'Gold AirPods',
'granny.png': '???',
'grass_block.png': 'Grass Block',
'grass_block-1.png': 'Grass Block (Duplicate)',
'grass.png': 'Grass Block All Sides',
'gs-2.png': 'Ghost',
'guys.png': 'Yellow Roblox Head',
'hat-1.png': 'White Hat (Duplicate)',
'hat.png': 'White Hat',
'hd-2.png': 'New Funky Mode',
'hd-1.png': 'New Funky Mode (Broken)',
'hdhead-1.png': 'HD Skin (Blue Hair)',
'hdhead.png': 'HD Skin (Galaxy)',
'hdhead-2.png': 'Silly Dog',
'doggo.png': 'Dog',
'head-1.png': 'Cursed Laughing Emoji',
'head-3.png': 'Cursed Laughing Emoji (Duplicate)',
'head-2.png': 'Notch',
'head-4.png': 'Doge',
'head-5.png': 'Roblox',
'headset.png': 'Headset',
'hell.png': '???',
'hi-1.png': '??? Boy (Duplicate)',
'hi.png': '??? Boy',
'hi-2.png': 'Sock',
'iphone-1.png': 'iPhone',
'iphone.png': 'iPhone Red',
'james.png': 'James Charles',
'jerry.png': '??? Boy',
'jj.png': 'Jodlum Jolt Energy Drink',
'kitty.png': 'Kitty Filter',
'l.png': '??? Minecraft',
'leo-1.png': '??? Man (Duplicate)',
'leo.png': '??? Man',
'librarian.png': 'Librarian Villager Hat',
'lion.png': 'Lion',
'thonk-thing.png': 'Thonking Emoji (Runaiic)',
'lol-1.png': 'Fortnite Logo',
'lol-2.png': 'Furries Hugging',
'lol-3.png': 'Random Noise',
'lol.png': 'Will Smith Alladin Genie',
'loss.png': 'Stock Image Loss',
'm-1.png': 'Beard',
'manga.png': 'Mango',
'mask-1.png': 'Pixel Mask (IllagerCaptain)',
'mask-2.png': "Majora's Mask",
'mask.png': 'Black Mask',
'master.png': 'Master Chief Helmet',
'maybe.png': 'Furret Art',
'me-1.png': '??? Man Thumbs Up',
'melon.png': 'Creepy Melon',
'memes.png': 'TF2 Spy Memes',
'milk.png': 'Man with Milk',
'nc.png': 'Shadow Nice Cock',
'nether_reactor_core.png': 'Nether Reactor Core',
'netherite_helmet.png': 'Netherite Helmet',
'netherrack.png': 'Netherrack',
'next-1.png': "You're Next (Duplicate)",
'next.png': "You're Next",
'nice.png': '??? Minecraft Character',
'note-1.png': 'Invisible',
'note.png': 'Invisible (Small)',
'noticed-1.png': 'Distorted Eating (Duplicate)',
'noticed-2.png': 'Distorted Eating (Duplicate)',
'noticed.png': 'Distorted Eating',
'obsidian.png': 'Obsidian',
'ok-1.png': 'Cat Surprised (Duplicate)',
'ok.png': 'Cat Surprised',
'one.png': 'Chinese One',
'oops.png': 'Bisken',
'packet.png': 'Paper Bag Mask',
'mrwolfhead222.png': 'Furry',
'airpodheaddd.png': 'AirPods with Shadow',
'airpods.png': 'Pixel AirPods (Runaiic)',
'pat.png': 'Putin and Obama',
'pc.png': 'Computer PC with Minecraft',
'penguin.png': 'Blue Club Penguin',
'pepe.png': 'Sad Pepe FeelsBadMan',
'pocket-1.png': 'Paper Bag Mask 2 (Duplicate)',
'pocket-2.png': 'Paper Bag Mask 2 (Duplicate)',
'pocket.png': 'Paper Bag Mask 2',
'pop.png': 'One Punch Man Expressionless',
'pppp.png': 'Sailor Moon Happy',
'pre.png': '??? Boy',
'pumpkin.png': 'Jack-O-Lantern',
'punch-1.png': 'One Punch Man (Duplicate)',
'punch.png': 'One Punch Man',
'quartz_block.png': 'Quartz Block',
'rainbow-1.png': 'Rainbow',
'rainbow.png': 'Rainbow AirPods',
'reddit.png': 'Poop (Actual Picture)',
'rogers.png': 'Rogers',
'rrr.png': 'Walter Dog / Nelson',
'ruby.png': 'Ruby Helmet',
'russian.png': 'Russian Sleep Experiment Mask',
'sh.png': '??? Helmet',
'signature.png': 'Dublin 2019',
'silence.png': 'Silence Liberal',
'sin.png': '??? Man with Tongue Out',
'skin-2.png': 'Hatsune Miku',
'skin-3.png': 'Kurumi Tokisaki',
'skin-4.png': 'Kurumi Tokisaki (Duplicate)',
'skin-5.png': 'Kurumi Tokisaki (Duplicate)',
'skin-6.png': 'Kurumi Tokisaki (Duplicate)',
'skin-7.png': 'Ricardo',
'skin-8.png': 'Gear',
'skin-10.png': '??? Boy',
'skin-11.png': '??? Boy (Duplicate)',
'skin-12.png': 'Side Colors',
'skin-13.png': '??? Boy',
'snapchat-1.png': 'Snapchat (Duplicate)',
'snapchat-2.png': 'Snapchat (Duplicate)',
'space.png': 'Space Galaxy',
'sphere.png': 'Cow Sphere Head',
'sponge.png': 'Sponge',
'ss-1.png': 'Big Toilet Paper',
'ss.png': 'Square Squidward',
'sss.png': 'Club Penguin',
'star-1.png': 'Christmas Tree Star',
'stone.png': 'Stone Block',
'stopsign.png': 'Stop Sign',
'sunglasses-1.png': 'Sunglasses',
'sunglasses-2.png': 'Pixel Sunglasses (Lisa1051)',
'sunglasses-3.png': 'Pixel Sunglasses (Small)',
'sunglasses.png': 'Pixel Sunglasses (Duplicate)',
'surprised.png': 'Surprised Pikachu',
'switch.png': 'Nintendo Switch Ad',
'template-2.png': 'NSFW Anime Art TriHard Edit',
'template-3.png': 'NSFW Ahegao',
'test-2.png': 'Violin',
'test-4.png': 'NSFW Penis Clipart',
'test-5.png': 'Hello Vlam',
'test-6.png': 'Hello Vlam (Duplicate)',
'test-7.png': 'Instagram',
'test-8.png': 'Instagram (Duplicate)',
'test-9.png': 'Instagram (Duplicate)',
'test-10.png': 'Fuzzy Skin',
'testing.png': '??? Girl',
'thinking.png': 'Thinking Emoji',
'three.png': 'Chinese Three',
'tnt.png': 'TNT',
'tom.png': 'Tom the Cat',
'transparent.png': 'Transparent Black',
'two.png': 'Chinese Two',
'ui.png': 'Discord',
'ui-1.png': 'Discord (Duplicate)',
'uwu-1.png': 'UwU Blush (Duplicate)',
'uwu-2.png': 'UwU',
'uwu-3.png': 'UwU (Duplicate)',
'villager.png': 'Villager',
'vine.png': 'Vine',
'white.png': 'GG',
'white-1.png': 'GG (Duplicate)',
'work-1.png': '??? Boy',
'work.png': 'Flower Crown Girl Skin',
'works.png': 'Lapex Clan Member',
'yea.png': 'Shrek Mike Wazowski',
'yes.png': 'Anime Swimming Party',
'sofancyhat.png': 'Top Hat (Runaiic)',
'skyrim.png': 'Skyrim Nintendo Switch (Runaiic)',
'nesshatx512.png': 'Ness Hat (Xiione)',
'UltraHDtest.png': 'Very Very Very Big Image (Runaiic)',
'Head.png': 'Color Sides',
'There.png': 'Panda',
'Dog.png': 'Dog with Wings',
'Eat.png': 'Toriel Eat Ur Pie My Child',
'Happy.png': 'Happy Emoji',
'Model.png': '???',
'rslashplace-1.png': 'r/Place (Runaiic)',
'Picture.png': "I'm Epic",
'Test.png': '??? Face',
'Arrow.png': 'Arrow',
'Bronze.png': 'Bronze Pot',
'Cage.png': 'Cage',
'Silver.png': 'Silver Pot',
'lisamask.png': 'Lisa Mask',
'sunglasses-t.png': 'Pixel Sunglasses (Lisa1051)',
'chessboard.png': 'Chess Board (Lisa1051)',
'hdts.png': 'Sunglasses (Lisa1051)',
'Skull-1.png': 'Creepy Skull (Duplicate)',
'Skull-2.png': 'Creepy Skull 2',
'Skull-3.png': 'Dark Skull',
'Xbox1.png': 'Xbox Logo',
'Zombie.png': 'Zombie Icon',
'Adidas.png': 'Adidas Logo',
'Anime-1.png': 'Anime Girl',
'Anime-2.png': 'Anime Girl (Duplicate)',
'Anime-3.png': 'Anime Girl (Duplicate)',
'Anime-4.png': 'Anime Girl (Duplicate)',
'Anime.png': 'Anime Girl (Duplicate)',
'Antonio.png': '??? Boy',
'Antonio-1.png': '??? Boy (Duplicate)',
'TAMOHAT.png': 'Teemo Hat (Runaiic)',
'SomeHeadphones.png': 'Headphones (Runaiic)',
'mario-hat.png': 'Mario Hat (Runaiic)',
'santa_hat.png': 'Santa Hat (Runaiic)',
'santa_hat2.png': 'Santa Hat 2 (Runaiic)',
'euleridentity.png': "Euler's Identity (Runaiic)",
'Chelsea.png': 'Chelsea Football Club',
'E.png': 'E Sign',
'Hacker.png': 'Anonymous Hacker Mask',
'Frog.png': 'Frog',
'Hentai.png': 'NSFW Hentai',
'Jesus.png': '??? Boy',
'Keyboard.png': 'Keyboard',
'Mono.png': 'Monocle',
'Mono-1.png': 'Monocle (Duplicate)',
'Mono-2.png': 'Monocle (Duplicate)',
'Mono-3.png': 'Monocle (Duplicate)',
'Mono-4.png': 'Monocle (Duplicate)',
'Morgan.png': '??? Minecraft Character',
'OakLog.png': 'HD Oak Log',
'Rick.png': 'Rick Astley',
'Rules.png': 'Rules (JackGrylls/Mutahar)',
'Saudi.png': "Saudi (That's the file name)",
'W.png': '??? Boy',
'William.png': '??? Boy',
'Windows.png': 'Windows Versions',
'FIX.png': 'Skin 64x64',
'JEW.png': 'Stereotypical Jew Meme',
'OWO.png': 'OwO',
'CROWN.png': 'Pixel Crown (Zyxraxth)',
'wynnadvert.png': 'WynnCraft Advertisement (Runaiic)',
'antimatter-explosive.png': 'Antimatter Explosive (Runaiic)',
'THONKONG.png': 'Thonking Emoji (Runaiic)',
'rage.png': 'A Real Cool Guy (LeiCha)',
'cock.png': 'NSFW Penis / Cock / Dick',
'Untitled-30.png':'Astronaut Helmet (Runaiic)',
'Untitled-31.png':'MapleStory Phantom Hat (Runaiic)',
'Untitled-32.png':'White Bear Hat (Runaiic)',
'Untitled-33.png':'Batman Mask (Runaiic)',
'Untitled-34.png':'Bread Hat (Runaiic)',
'Untitled-35.png':'Captain Hat (Runaiic)',
'Untitled-36.png':'Chameleon Hat Pet (Runaiic)',
'Untitled-37.png':'Chef Hat (Runaiic)',
'Untitled-38.png':'Crying Emoji Mask (Runaiic)',
'Untitled-39.png':'Doge Hat (Runaiic)',
'Untitled-40.png':'Dog Mask (Runaiic)',
'Untitled-41.png':'Chick Hat (Runaiic)',
'Untitled-42.png':'Egg on Head (Runaiic)',
'Untitled-43.png':'Evil Face Mask (Runaiic)',
'Untitled-44.png':'Knight Helmet (Runaiic)',
'Untitled-45.png':'Wolf Hat (Runaiic)',
'Untitled-46.png':'Balaclava Hat (Runaiic)',
'Untitled-47.png':'Mask (Runaiic)',
'Untitled-48.png':'Flower Crown (Runaiic)',
'Untitled-49.png':'Frog Hat (Runaiic)',
'Untitled-50.png':'Garfield Hat (Runaiic)',
'Untitled-51.png':'Forehead Sunglasses (Runaiic)',
'Untitled-52.png':'Steampunk Goggles (Runaiic)',
'Untitled-53.png':'Green Flower Crown (Runaiic)',
'Untitled-54.png':'Rainbow Flower Crown (Runaiic)',
'Untitled-55.png':'Halo (Runaiic)',
'Untitled-56.png':'Smile Mask (Runaiic)',
'Untitled-57.png':'Hong Kong Protestor Mask (Runaiic)',
'Untitled-58.png':'Black Kabuki Mask (Runaiic)',
'Untitled-59.png':'Laughing Emoji Mask (Runaiic)',
'Untitled-60.png':'McDonalds Hat (Runaiic)',
'Untitled-61.png':'Straw Hat (Runaiic)',
'Untitled-62.png':'Forehead Protector (Runaiic)',
'Untitled-63.png':'Football Helmet (Runaiic)',
'Untitled-64.png':'pepeL Mask (Runaiic)',
'Untitled-65.png':'Polar Bear Hat (Runaiic)',
'Untitled-66.png':'Police Hat (Runaiic)',
'Untitled-67.png':'Blue-Tinted Glasses (Runaiic)',
'Untitled-68.png':'Ram Hat (Runaiic)',
'Untitled-69.png':'Sheep Hat (Runaiic)',
'Untitled-70.png':'Squidward Mask (Runaiic)',
'Untitled-71.png':'Thinking Emoji Mask (Runaiic)',
'Untitled-72.png':"Red's Hat (Runaiic)",
'Untitled-73.png':"Wojak Smiling Mask (RyanUwU)",
}